# Site Settings
title: Mugdad Elneama
description: Data Analyst | Python, SQL, Power BI
logo: assets/img/profile_circular.png
show_downloads: false

# Theme Configuration
theme: jekyll-theme-minimal

# Personal Information
github_username: mugdadelneama
linkedin_username: mugdad-elneama-249a5a228
email: megdad.2003@gmail.com
location: Dubai, UAE
phone: "+971 56 675 4494"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# SEO Settings
author: Mugdad Elneama
social:
  name: Mugdad Elneama
  links:
    - https://www.linkedin.com/in/mugdad-elneama-249a5a228
    - https://github.com/mugdadelneama
